version: "3"

services:
  perros:
    build: ../microservices/perros-servicio

  premios:
    build: ../microservices/premios-servicio

  razas:
    build: ../microservices/razas-servicio

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - perros
      - premios
      - razas
